services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gorbushka_app
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/application
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
#    depends_on:
#      - postgres
#      - redis
#
#  postgres:
#    image: postgres:16-alpine
#    container_name: gorbushka_postgres
#    environment:
#      POSTGRES_DB: gorbushka
#      POSTGRES_USER: gorbushka
#      POSTGRES_PASSWORD: gorbushka
#    ports:
#      - "5432:5432"
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#
#  redis:
#    image: redis:7-alpine
#    container_name: gorbushka_redis
#    ports:
#      - "6379:6379"
#    volumes:
#      - redisdata:/data
#
#volumes:
#  pgdata:
#  redisdata:
